#!/bin/bash
#PBS -l select=1:ncpus=32
#PBS -l walltime=10:00:00:00
#PBS -p 0
#PBS -N make
#PBS -j oe
#PBS -m abe 
#PBS -M joelnitta@gmail.com
#PBS -V
cd ftol
### start docker daemon
start-dockerd.sh
### wait for docker daemon to get up and running
sleep 30
### mount ~ so symlinks to ~/project_data work
docker run --rm -v ~/:/home/rstudio/ -w /home/rstudio/ftol joelnitta/ftol:4.0.0 Rscript -e "drake::r_make()"
### stop docker daemon
stop-dockerd.sh
